sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t johnahn/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true johnahn/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: Docker-react-app-env
  bucket_name: elasticbeanstalk-us-east-1-211125418324
  bucket_path: docker-react-app
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
